#input query instead of 'here'
node ..\src\app.js '#1, type RSDSHORT, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1561)
RSDODBC               Parameter\Input                         #2, type RSDSHORT, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1561)
RSDODBC               Parameter\Input                         #3, type RSDDATE, value: 0.0.0                                                                                                                                                                                 4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1714)
RSDODBC               Parameter\Input                         #4, type RSDDATE, value: 31.12.9999                                                                                                                                                                            4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1714)
RSDODBC               Parameter\Input                         #5, type RSDSHORT, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1561)
RSDODBC               Parameter\Input                         #6, type RSDSHORT, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1561)
RSDODBC               Parameter\Input                         #7, type RSDCHAR, value: 0                                                                                                                                                                                     4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1633)
RSDODBC               Parameter\Input                         #8, type RSDCHAR, value: 0                                                                                                                                                                                     4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1633)
RSDODBC               Parameter\Input                         #9, type RSDTIME, value: 0:0:0                                                                                                                                                                                 4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1726)
RSDODBC               Parameter\Input                         #10, type RSDTIME, value: 23:59:59                                                                                                                                                                             4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1726)
RSDODBC               Parameter\Input                         #11, type RSDLONG, value: 9995                                                                                                                                                                                 4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #12, type RSDLONG, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #13, type RSDLONG, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #14, type RSDLONG, value: 9995                                                                                                                                                                                 4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #15, type RSDLONG, value: 9995                                                                                                                                                                                 4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #16, type RSDCHAR, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1633)
RSDODBC               Parameter\Input                         #17, type RSDLONG, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #18, type RSDCHAR, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1633)
RSDODBC               Parameter\Input                         #19, type RSDLONG, value: 9995                                                                                                                                                                                 4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #20, type RSDLONG, value: 0                                                                                                                                                                                    4        17:10:57.307 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #21, type RSDLONG, value: 9995                                                                                                                                                                                 4        17:10:57.308 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #22, type RSDLONG, value: 117826                                                                                                                                                                               4        17:10:57.308 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #23, type RSDCHAR, value: 88                                                                                                                                                                                   4        17:10:57.308 06-09-2022   RsdCmdSp.cpp (line 1633)
RSDODBC               Parameter\Input                         #24, type RSDLONG, value: 6                                                                                                                                                                                    4        17:10:57.308 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #25, type RSDLONG, value: 7                                                                                                                                                                                    4        17:10:57.308 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #26, type RSDLONG, value: 8                                                                                                                                                                                    4        17:10:57.308 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #27, type RSDLONG, value: 9                                                                                                                                                                                    4        17:10:57.308 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               Parameter\Input                         #28, type RSDLONG, value: 9995                                                                                                                                                                                 4        17:10:57.308 06-09-2022   RsdCmdSp.cpp (line 1577)
RSDODBC               SQL\Execute                             SELECT /*+FIRST_ROWS*/ t.t_id, t.t_type, t.t_branch, t.t_date, t.t_time, t.t_oper, t.t_brigade, t.t_processedby, t.t_isprocessed, t.t_state, t.t_desc, t.t_isnotice, t.t_recipient, t.t_audsid, t.t_priv       1        17:10:57.308 06-09-2022   RSDCommandO.cpp (line 610)
                                                              id, t.t_roleid, t.t_objecttype, t.t_objectid, t.t_confuncid, t.t_rejfuncid, t.t_param,t.T_FMTBLOBDATA_XXXX FROM dcritact_dbt t WHERE  (t.t_branch BETWEEN ? AND ?  AND t.t_date BETWEEN ? AND ?  AND t.t
                                                              _brigade BETWEEN ? AND ?  AND t.t_isprocessed BETWEEN ? AND ?  AND t.t_time BETWEEN ? AND ? ) AND  (t.t_id IN (select t3.t_id from dcritact_dbt t3 where t3.t_id NOT IN (select t2.t_critid from dcritac
                                                              t_dbt t1, dcritrecipnot_dbt t2 where t1.t_id=t2.t_critid AND t2.t_Oper=?) AND t3.t_RoleID=? AND (t3.t_Recipient=? OR t3.t_Recipient=?) union all select t4.t_id from dcritact_dbt t4, dcritrecipnot_dbt 
                                                              t5 where t4.t_id=t5.t_critid AND (t5.t_Oper=? AND t5.t_isview=? OR t4.t_RoleID=? AND t5.t_isview=? AND t5.t_Oper=? AND (t4.t_Recipient=? OR t4.t_Recipient=?)))) AND  (t.t_AudSid<>? AND (t.t_IsNotice=?
                                                               OR (((t.t_Type=? OR t.t_Type=?) OR t.t_Type=?) OR t.t_Type=? AND t.t_Oper<>?))) ORDER BY t.t_branch, t.t_date, t.t_brigade, t.t_isprocessed, t.t_time, t.t_id'
															   
pause															   
